### ISSUE TITLE
Decision agent crasht bij opstarten wanneer een SensorAgent verdwenen is.

### ISSUE THREAD

**Issue by rogierpijpers** [MSDA-LifeCycleAgents/brokeragent#32]
jan 26, 2018 2:27:04 PM com.mlaf.hu.decisionagent.behaviour.UpdateStatusSensorAgentBehaviour checkForInactivity
INFO: Removed/Unregistered Sensor Agent:
( agent-identifier :name sensor-agent-impl1@192.168.178.14:1099/JADE  :addresses (sequence http://192.168.178.14:7778/acc tcp://192.168.178.14:6789 ))
***  Uncaught Exception for agent decision-agent  ***
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
	at com.mlaf.hu.decisionagent.behaviour.UpdateStatusSensorAgentBehaviour.checkForInactivity(UpdateStatusSensorAgentBehaviour.java:40)
	at com.mlaf.hu.decisionagent.behaviour.UpdateStatusSensorAgentBehaviour.onTick(UpdateStatusSensorAgentBehaviour.java:34)
	at jade.core.behaviours.TickerBehaviour.action(TickerBehaviour.java:72)
	at jade.core.behaviours.Behaviour.actionWrapper(Behaviour.java:344)
	at jade.core.Agent$ActiveLifeCycle.execute(Agent.java:1585)
	at jade.core.Agent.run(Agent.java:1524)
	at java.lang.Thread.run(Thread.java:745)
ERROR: Agent decision-agent died without being properly terminated !!!
State was 2

**Comment by thijsgelton** [comment]
Can not recreate.
![image](https://user-images.githubusercontent.com/21140767/35501025-e472fece-04d8-11e8-9b31-84bea06a89d5.png)

With mine it seems to be working fine.

**Comment by thijsgelton** [comment]
Exception only occurs whenever the Decision Agent tries to write and unregister a Sensor Agent at the same time. Fixed this by addinga  boolean value to the Decision Agent called: isUpdatingStatus. This way the DA won't try to write to disk when it's updating.
